version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}
                      - v1-dependencies-

            - run: yarn install

            - save_cache:
                  paths:
                      - node_modules
                      - ~/.cache/yarn
                  key: v1-dependencies-{{ checksum "yarn.lock" }}

            - run: npx semantic-release
            #- run: yarn test --ci --runInBand
